services:
  postgres-db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres-db
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - PGHOST=${PGHOST}
      - PGUSER=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=${PGPASSWORD}
      - PGPORT=5432
      - ACCESS_TOKEN=${ACCESS_TOKEN}

volumes:
  postgres-data: